// Code generated by sqlc. DO NOT EDIT.
// source: transfer.sql

package db

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
  sender_id,
  reciepent_id,
  amount
) VALUES (
  $1, $2, $3
) RETURNING id, reciepent_id, sender_id, amount, created_at, updated_at, deleted_at
`

type CreateTransferParams struct {
	SenderID    int64 `json:"sender_id"`
	ReciepentID int64 `json:"reciepent_id"`
	Amount      int64 `json:"amount"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.queryRow(ctx, q.createTransferStmt, createTransfer, arg.SenderID, arg.ReciepentID, arg.Amount)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ReciepentID,
		&i.SenderID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, reciepent_id, sender_id, amount, created_at, updated_at, deleted_at FROM transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.queryRow(ctx, q.getTransferStmt, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ReciepentID,
		&i.SenderID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, reciepent_id, sender_id, amount, created_at, updated_at, deleted_at FROM transfers
WHERE 
    sender_id = $1 OR
    reciepent_id = $2
ORDER BY id
LIMIT $3
OFFSET $4
`

type ListTransfersParams struct {
	SenderID    int64 `json:"sender_id"`
	ReciepentID int64 `json:"reciepent_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error) {
	rows, err := q.query(ctx, q.listTransfersStmt, listTransfers,
		arg.SenderID,
		arg.ReciepentID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.ReciepentID,
			&i.SenderID,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
